#!/usr/bin/python
#
# Project Name:  unshac.py
# File:          conffile.py
# Author:        Nina Alexandra Klama
# License:       GPL v3 (see included LICENSE file)
#
# This script is supposed to unify the shell environment on several machines,
# while still allowing for individual differences on each machine
#

import os.path as path

from confModule import ConfModule


class ConfFiles(ConfModule):
  def __init__(self, shell):
    self.files = []
    self.generatedString = " File generated by unshac.py changes will be overwritten"

  def __call__(self, shell=None):
    outFiles = {}
    home = path.expanduser("~")
    for f in self.files:
      fName = path.join(home, f['path'])
      overwrite = f['overwrite']
      if not overwrite:
        if path.exists(fName) and path.file(fName):
          checkLine = f['comment'] + self.generatedString
          testLine  = ""
          with open(fName, 'r') as F:
            testLine = F.readline()
          if testLine == checkLine:
            overwrite = True
      if overwrite:
        outFiles[fName] = f['lines']
    return outFiles

  def addFileList(self, path, lines, commentPre="#", overwrite=True):
    self.files.append(
      {
        'path':       path,
        'lines':      lines,
        'comment':    commentPre,
        'overwrite':  overwrite
      })

  def addFile(self, path, text, commentPre="#", overwrite=True):
    lines = text.splitlines()
    self.addFileList(path, lines, commentPre, overwrite)
